# Generated by Django 6.0.2 on 2026-02-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
