# Generated by Django 6.0.2 on 2026-02-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='languages',
        ),
    ]
