# Generated by Django 6.0.2 on 2026-02-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_teacherprofile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
