# Generated by Django 6.0.2 on 2026-02-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
