# Generated by Django 6.0.2 on 2026-02-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_profile_picture'),
        ('scheduling', '0006_lesson_unique_booking_per_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='payout_day',
            field=models.PositiveSmallIntegerField(default=25, help_text='Day of month on which teacher receives salary payout (1-28)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='rate_per_lesson_uzs',
            field=models.DecimalField(decimal_places=0, default=0, help_text="Teacher's pay per 1-hour lesson in UZS (set by admin)", max_digits=12),
        ),
        migrations.CreateModel(
            name='EarningsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lesson_credit', 'Lesson Credit'), ('adjustment', 'Manual Adjustment'), ('payout', 'Payout'), ('correction', 'Correction')], max_length=20)),
                ('amount_uzs', models.DecimalField(decimal_places=0, help_text='Positive = credit (earned/bonus), negative = debit (deduction/payout)', max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('payout_ref', models.CharField(blank=True, help_text='Bank transfer reference', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings_events', to='scheduling.lesson')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.PROTECT, related_name='earnings_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Earnings Event',
                'verbose_name_plural': 'Earnings Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
