# Generated by Django 6.0.2 on 2026-02-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_teacherprofile_payout_day_and_more'),
        ('payments', '0001_initial'),
        ('scheduling', '0007_lesson_credits_consumed_lesson_no_show_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='churn_reason',
            field=models.TextField(blank=True, help_text='Reason for churn (set when crm_status = churned)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='crm_status',
            field=models.CharField(choices=[('lead', 'Lead'), ('trial', 'Trial'), ('paying', 'Paying'), ('inactive', 'Inactive'), ('churned', 'Churned')], default='lead', help_text='CRM lifecycle stage for this student', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. "VIP, at-risk, scholarship"', max_length=255),
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_authored', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Note',
                'verbose_name_plural': 'Admin Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Credits added (positive) or removed (negative)')),
                ('reason_code', models.CharField(choices=[('purchase', 'Credit Purchase'), ('lesson', 'Lesson Consumed'), ('admin_add', 'Admin Gift/Adjustment'), ('admin_sub', 'Admin Deduction'), ('refund', 'Refund')], max_length=20)),
                ('reason_detail', models.TextField(blank=True, help_text='Human-readable explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='scheduling.lesson')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='payments.payment')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
