# Generated by Django 6.0.2 on 2026-02-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_studentprofile_churn_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnote',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='accounts.studentprofile'),
        ),
    ]
