# Generated by Django 6.0.2 on 2026-02-20 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_adminnote_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('student_registered', 'Student Registered'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('payment_manual', 'Manual Payment'), ('credits_adjusted', 'Credits Adjusted'), ('lesson_scheduled', 'Lesson Scheduled'), ('lesson_cancelled', 'Lesson Cancelled'), ('lesson_completed', 'Lesson Completed'), ('lesson_absent', 'Student Absent'), ('teacher_payout', 'Teacher Payout'), ('admin_note_added', 'Admin Note Added')], db_index=True, max_length=30)),
                ('payment_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lesson_id_ref', models.PositiveIntegerField(blank=True, null=True)),
                ('credit_tx_id', models.PositiveIntegerField(blank=True, null=True)),
                ('earnings_event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('subject_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='accounts.studentprofile')),
                ('subject_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='accounts.teacherprofile')),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='accounts_ac_created_114745_idx'), models.Index(fields=['event_type'], name='accounts_ac_event_t_95e84a_idx'), models.Index(fields=['subject_student', 'created_at'], name='accounts_ac_subject_b51fac_idx'), models.Index(fields=['subject_teacher', 'created_at'], name='accounts_ac_subject_9531b7_idx')],
            },
        ),
    ]
