# Generated by Django 6.0.2 on 2026-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='credits_reserved',
            field=models.PositiveIntegerField(default=0, help_text='Credits currently held for upcoming/in-progress lessons'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='reason_code',
            field=models.CharField(choices=[('purchase', 'Credit Purchase'), ('lesson', 'Lesson Consumed'), ('student_absent', 'Student Absent – Charged'), ('admin_add', 'Admin Gift/Adjustment'), ('admin_sub', 'Admin Deduction'), ('refund', 'Refund')], max_length=20),
        ),
    ]
