# Generated by Django 6.0.2 on 2026-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_activityevent_id_alter_adminnote_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useridentity',
            unique_together={('provider', 'provider_id'), ('user', 'provider')},
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='language_certificates',
            field=models.JSONField(blank=True, default=list, help_text='List of {certificate_name, score, issued_date, certificate_file_url} objects'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='pending', help_text='Only active teachers are shown in the public listing', max_length=20),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='email',
            field=models.CharField(blank=True, help_text='Email from provider (Google)', max_length=255),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useridentity',
            name='username',
            field=models.CharField(blank=True, help_text='Username from provider (Telegram)', max_length=255),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='adminnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='earningsevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of {language, proficiency} objects. Proficiency: Native|Fluent|Intermediate|Basic'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useridentity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
