# Generated by Django 5.0.4 on 2026-04-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_alter_announcement_id_alter_banner_id_and_more"),
        ("marketing", "0004_add_is_archived_to_banner_announcement"),
    ]

    operations = []
