# Generated by Django 6.0.2 on 2026-02-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaking', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')])),
                ('grammar', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')])),
                ('vocabulary', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')])),
                ('listening', models.IntegerField(choices=[(1, 'Very bad'), (2, 'Bad'), (3, 'OK'), (4, 'Good'), (5, 'Excellent')])),
                ('teacher_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='lessons.lesson')),
            ],
        ),
    ]
