# Generated by Django 6.0.2 on 2026-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('placement', models.CharField(choices=[('student_home_top', 'Student Home Top'), ('teacher_home_top', 'Teacher Home Top')], default='student_home_top', max_length=40)),
                ('target_role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('BOTH', 'Both')], default='STUDENT', max_length=10)),
                ('image_web', models.ImageField(blank=True, null=True, upload_to='banners/web/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='banners/mobile/')),
                ('background_color', models.CharField(blank=True, help_text='Hex color, e.g. #4A90E2', max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=140, null=True)),
                ('cta_text', models.CharField(blank=True, max_length=40, null=True)),
                ('target_type', models.CharField(choices=[('INTERNAL', 'Internal Route'), ('EXTERNAL', 'External URL')], default='INTERNAL', max_length=10)),
                ('target_value', models.CharField(help_text='Route path for INTERNAL, full URL for EXTERNAL', max_length=255)),
                ('priority', models.IntegerField(default=0, help_text='Higher shows first')),
                ('is_active', models.BooleanField(default=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner Campaign',
                'verbose_name_plural': 'Banner Campaigns',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
