# Generated by Django 6.0.2 on 2026-02-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercampaign',
            name='placement',
            field=models.CharField(choices=[('student_home_top', 'Student Home Top'), ('teacher_home_top', 'Teacher Home Top'), ('classroom_waiting', 'Classroom Waiting Screen')], default='student_home_top', max_length=40),
        ),
    ]
