# Generated by Django 6.0.2 on 2026-02-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_alter_bannercampaign_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercampaign',
            name='placement',
            field=models.CharField(choices=[('student_home_top', 'Student Home Top'), ('teacher_home_top', 'Teacher Home Top')], default='student_home_top', max_length=40),
        ),
    ]
