# Generated by Django 6.0.2 on 2026-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_alter_bannercampaign_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercampaign',
            name='target_type',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal Route'), ('EXTERNAL', 'External URL')], default='INTERNAL', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bannercampaign',
            name='target_value',
            field=models.CharField(blank=True, help_text='Route path for INTERNAL, full URL for EXTERNAL', max_length=255, null=True),
        ),
    ]
