# Generated by Django 6.0.2 on 2026-02-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_bannercampaign_target_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercampaign',
            name='target_platform',
            field=models.CharField(choices=[('WEB', 'Web only'), ('MOBILE', 'Mobile only'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
    ]
