# Generated by Django 5.2.11 on 2026-03-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_alter_bannercampaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercampaign',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
