# Generated by Django 6.0.2 on 2026-03-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_alter_bannercampaign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannercampaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
