# Generated by Django 6.0.2 on 2026-02-16 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='selected_option',
        ),
        
        
        migrations.RemoveField(
            model_name='homeworkassignment',
            name='total_points',
        ),
        migrations.AddField(
            model_name='homeworkassignment',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='HomeworkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('quiz', 'Multiple Choice Quiz'), ('gap_fill', 'Fill in the Blanks'), ('matching', 'Matching Pairs')], max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('points', models.IntegerField(default=10)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='homework.homework')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_data', models.JSONField()),
                ('is_correct', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.homeworkactivity')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='homework.homeworkassignment')),
            ],
            options={
                'unique_together': {('assignment', 'activity')},
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
