# Generated by Django 6.0.2 on 2026-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_remove_studentanswer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkactivity',
            name='activity_type',
            field=models.CharField(choices=[('quiz', 'Multiple Choice Quiz'), ('gap_fill', 'Fill in the Blanks'), ('matching', 'Matching Pairs'), ('listening', 'Listening Task')], max_length=20),
        ),
    ]
