# Generated by Django 5.2.11 on 2026-02-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_alter_homeworkactivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homeworkactivity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homeworkassignment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentactivityresponse',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
