# Generated by Django 6.0.2 on 2026-02-11 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='availability_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_lessons', to='scheduling.availability'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='room_sid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
