# Generated by Django 6.0.2 on 2026-02-11 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_lesson_availability_slot_lesson_lesson_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='room_sid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
