# Generated by Django 6.0.2 on 2026-02-13 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_lesson_room_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('student_absent', 'student_absent'), ('technical_issues', 'technical_issues')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('matching', 'Matching Game'), ('gap_fill', 'Gap Fill'), ('quiz', 'Quiz')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('lesson_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='scheduling.lessontemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
