# Generated by Django 6.0.2 on 2026-02-20 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_lesson_ended_at_alter_lesson_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('availability_slot', 'lesson_date'), name='unique_booking_per_slot_date'),
        ),
    ]
