# Generated by Django 6.0.2 on 2026-02-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_lesson_unique_booking_per_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='credits_consumed',
            field=models.BooleanField(default=False, help_text='True when a student credit was deducted for this lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='no_show_reason',
            field=models.CharField(blank=True, help_text='Reason recorded when student was absent or lesson cancelled', max_length=255),
        ),
    ]
