# Generated by Django 6.0.2 on 2026-02-21 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_lesson_credits_consumed_lesson_no_show_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonWrapUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('homework_text', models.TextField(blank=True, default='')),
                ('homework_due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wrap_up', to='scheduling.lesson')),
            ],
        ),
    ]
