# Generated by Django 6.0.2 on 2026-02-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_lesson_wrap_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='credits_reserved',
            field=models.BooleanField(default=False, help_text='True when a credit hold has been placed at booking time'),
        ),
    ]
