# Generated by Django 6.0.2 on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_credits_reserved'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE scheduling_lesson
                            ADD COLUMN IF NOT EXISTS active_students_count integer;
                        ALTER TABLE scheduling_lesson
                            ADD COLUMN IF NOT EXISTS active_teacher boolean;
                        ALTER TABLE scheduling_lesson
                            ADD COLUMN IF NOT EXISTS room_empty_since timestamptz NULL;
                        ALTER TABLE scheduling_lesson
                            ADD COLUMN IF NOT EXISTS session_ended_at timestamptz NULL;
                        ALTER TABLE scheduling_lesson
                            ADD COLUMN IF NOT EXISTS teacher_joined_at timestamptz NULL;
                        ALTER TABLE scheduling_lesson
                            ADD COLUMN IF NOT EXISTS teacher_left_at timestamptz NULL;

                        UPDATE scheduling_lesson
                        SET active_students_count = 0
                        WHERE active_students_count IS NULL;

                        UPDATE scheduling_lesson
                        SET active_teacher = FALSE
                        WHERE active_teacher IS NULL;

                        ALTER TABLE scheduling_lesson
                            ALTER COLUMN active_students_count SET DEFAULT 0;
                        ALTER TABLE scheduling_lesson
                            ALTER COLUMN active_teacher SET DEFAULT FALSE;

                        ALTER TABLE scheduling_lesson
                            ALTER COLUMN active_students_count SET NOT NULL;
                        ALTER TABLE scheduling_lesson
                            ALTER COLUMN active_teacher SET NOT NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE scheduling_lesson DROP COLUMN IF EXISTS teacher_left_at;
                        ALTER TABLE scheduling_lesson DROP COLUMN IF EXISTS teacher_joined_at;
                        ALTER TABLE scheduling_lesson DROP COLUMN IF EXISTS session_ended_at;
                        ALTER TABLE scheduling_lesson DROP COLUMN IF EXISTS room_empty_since;
                        ALTER TABLE scheduling_lesson DROP COLUMN IF EXISTS active_teacher;
                        ALTER TABLE scheduling_lesson DROP COLUMN IF EXISTS active_students_count;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='lesson',
                    name='active_students_count',
                    field=models.IntegerField(
                        default=0,
                        help_text='Number of students currently present in the live classroom session',
                    ),
                ),
                migrations.AddField(
                    model_name='lesson',
                    name='active_teacher',
                    field=models.BooleanField(
                        default=False,
                        help_text='True while the assigned teacher is connected in the live classroom',
                    ),
                ),
                migrations.AddField(
                    model_name='lesson',
                    name='room_empty_since',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lesson',
                    name='session_ended_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lesson',
                    name='teacher_joined_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='lesson',
                    name='teacher_left_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
    ]
