# Generated by Django 6.0.2 on 2026-02-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_amount', models.PositiveIntegerField(help_text='Credits purchased in this transaction')),
                ('amount_uzs', models.DecimalField(decimal_places=0, help_text='Total amount paid in UZS (Uzbek soʻm)', max_digits=14)),
                ('currency', models.CharField(default='UZS', editable=False, max_length=3)),
                ('method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('transfer', 'Bank Transfer'), ('manual', 'Manual (Admin)')], default='test', max_length=20)),
                ('provider', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('apelsin', 'Apelsin'), ('manual', 'Manual'), ('test', 'Test (Demo)')], default='test', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('receipt_id', models.CharField(blank=True, help_text='Provider transaction ID or reference', max_length=255)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_holder_name', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
