# Generated by Django 6.0.2 on 2026-03-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_subject_alter_activityevent_id_alter_adminnote_id_and_more'),
        ('payments', '0002_add_stripe_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lessons_count', models.PositiveIntegerField(help_text='Number of lessons included in this package')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('validity_days', models.PositiveIntegerField(help_text='Days from purchase until the package expires')),
                ('is_active', models.BooleanField(default=True, help_text='Only active packages are shown to students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='StudentPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_lessons', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('USED', 'Used')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_packages', to='payments.package')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_packages', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Package',
                'verbose_name_plural': 'Student Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
