# Generated by Django 6.0.2 on 2026-02-12 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Activity', max_length=200)),
                ('activity_type', models.CharField(choices=[('image', 'Image Presentation'), ('video', 'Video Embed'), ('matching', 'Matching Game'), ('gap_fill', 'Fill in the Blanks'), ('quiz', 'Multiple Choice Quiz')], default='image', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='curriculum.lesson')),
            ],
            options={
                'verbose_name_plural': 'Lesson Activities',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
