# Generated by Django 6.0.2 on 2026-02-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_lessonactivity_delete_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='slides_pdf',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
