# Generated by Django 6.0.2 on 2026-02-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_remove_lesson_slides_pdf_remove_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slides_pdf',
            field=models.FileField(blank=True, null=True, upload_to='lessons/pdfs/'),
        ),
    ]
