# Generated by Django 6.0.2 on 2026-02-23 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_pdfasset_lessonactivity_pdf_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonactivity',
            name='activity_type',
            field=models.CharField(choices=[('image', 'Image Presentation'), ('video', 'Video Embed'), ('matching', 'Matching Game'), ('gap_fill', 'Fill in the Blanks'), ('quiz', 'Multiple Choice Quiz'), ('pdf', 'PDF Viewer'), ('listening', 'Listening Task')], default='image', max_length=20),
        ),
        migrations.CreateModel(
            name='AudioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
