# Generated by Django 6.0.2 on 2026-03-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0023_subject_alter_activityevent_id_alter_adminnote_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cost_in_coins', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True, help_text='Only active rewards are visible to students')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['cost_in_coins'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive = earned, negative = spent')),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Coin Transaction',
                'verbose_name_plural': 'Coin Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLAIMED', 'Claimed'), ('APPROVED', 'Approved'), ('SHIPPED', 'Shipped')], default='CLAIMED', max_length=10)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_rewards', to='gamification.reward')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_rewards', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Reward',
                'verbose_name_plural': 'Student Rewards',
                'ordering': ['-claimed_at'],
            },
        ),
    ]
