# Generated by Django 6.0.2 on 2026-03-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_telegram', '0002_alter_telegramaccount_id_alter_telegramlogintoken_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramlogintoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
