# Generated by Django 6.0.2 on 2026-02-08 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_notes', models.TextField(blank=True, help_text='Private notes for the teacher')),
                ('whiteboard_data', models.JSONField(blank=True, default=dict, help_text='Canvas data for the whiteboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='scheduling.lesson')),
            ],
        ),
    ]
